### ISSUE TITLE
1.21.2 support

### ISSUE THREAD

**Issue by BlueStaggo** [0x000006/vertical-bobbing#1]
I've updated the mod for 1.21.2 for you here: https://github.com/BlueStaggo/vertical-bobbing

1.21.2 made a breaking change that changed the type of the `playerEntity` variable in `GameRenderer.bobView` from `PlayerEntity` into `AbstractClientPlayerEntity`. It was a simple one-line fix. I hope that by making this issue, I bring this to your attention.

**Comment by 0x000006** [comment]
Thanks for your help, I appreciate it. I'm currently working on a v1.1 for all versions. I will commit it soon and upload it to Modrinth.

**Comment by 0x000006** [comment]
Done.
