### ISSUE TITLE
Bobbing upon falling is not smooth

### ISSUE THREAD

**Issue by BlueStaggo** [0x000006/vertical-bobbing#3]
In this mod, upon falling to the ground, vertical bobbing snaps back to eye level in a single tick. However, in older versions of Minecraft, this seems to be smoother:

https://github.com/user-attachments/assets/0316b996-440a-439c-b50b-edadade2d0d1

Take a closer look at the clouds and the first person hand and it doesn't quite line up. I've tested versions 1.0 and 1.2 of this mod on 1.21.

**Comment by 0x000006** [comment]
V1.3 will implement the original code from older versions. My goal wasn't to make it exactly the same as the old versions but similar to it.
