### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lowercasebtw** [0x000006/vertical-bobbing#4]
https://github.com/BlueStaggo/vertical-bobbing/blob/1.21.2/src/main/java/zerox06/vertical/bobbing/mixin/GameRendererMixin.java#L23

Why is this there? This wasn't in the code prior, before it was removed.

**Comment by lowercasebtw** [comment]
Same for the multiplying of 5

**Comment by 0x000006** [comment]
I wanted to replicate the view bobbing in older versions but never got to look at the original code. My goal wasn't to replicate it 1:1 perfectly but make it look really accurate to the original one. V1.3 will implement the original behavior as it was.
